# Generated by Django 3.2.9 on 2021-12-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
